### ISSUE TITLE
ARM PHP Docker

### ISSUE THREAD

**Issue by tuefekci** [tuefekci/blkhole#3]
```

Stack trace:

#0 /srv/blkhole/vendor/amphp/amp/lib/Internal/Placeholder.php(46): GT\BLK\Web->GT\BLK\{closure}(NULL, true)

#1 /srv/blkhole/app/web.php(94): Amp\Coroutine->onResolve(Object(Closure))

#2 [internal function]: GT\BLK\Web->GT\BLK\{closure}(Object(Amp\Http\Server\Request))

#3 /srv/blkhole/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send('{"magnet":"magn...')

#4 /srv/blkhole/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, '{"magnet":"magn...')

#5 /srv/blkhole/vendor/amphp/amp/lib/Coroutine.php(123): Amp\Coroutine->resolve('{"magnet":"magn...')

#6 /srv/blkhole/vendor/amphp/amp/lib/Internal/Placeholder.php(149): Amp\Coroutine->Amp\{closure}(NULL, NULL)

#7 /srv/blkhole/vendor/amphp/amp/lib/Deferred.php(53): class@anonymous->resolve(NULL)

#8 /srv/blkhole/vendor/amphp/byte-stream/lib/IteratorStream.php(64): Amp\Deferred->resolve()

#9 /srv/blkhole/vendor/amphp/amp/lib/Succe in /srv/blkhole/app/web.php on line 90


********************************************************************************

```

**Comment by tuefekci** [comment]
Fatal error: Uncaught Error: Class 'tuefekci\helpers\Strings' not found in /srv/blkhole/app/web.php:90
