### ISSUE TITLE
PHP7.4 ARM Docker

### ISSUE THREAD

**Issue by tuefekci** [tuefekci/blkhole#4]
It kinda gets annoying that they are behaving so differently :/ 

```
Fatal error: Uncaught Amp\Http\Client\ParseException: Configured body size exceeded: 1777340416 bytes received, while the configured limit is 1777336320 bytes in /srv/blkhole/vendor/amphp/http-client/src/Connection/Internal/Http1Parser.php:447

Stack trace:

#0 /srv/blkhole/vendor/amphp/http-client/src/Connection/Internal/Http1Parser.php(202): Amp\Http\Client\Connection\Internal\Http1Parser->addToBody('\xC1\xF9\x80\x96\xD3p\xCB\x8D!,\x8A\x8A\xAE\xCC\xC4...')

#1 /srv/blkhole/vendor/amphp/http-client/src/Connection/Http1Connection.php(410): Amp\Http\Client\Connection\Internal\Http1Parser->parse('\xC1\xF9\x80\x96\xD3p\xCB\x8D!,\x8A\x8A\xAE\xCC\xC4...')

#2 [internal function]: Amp\Http\Client\Connection\Http1Connection->Amp\Http\Client\Connection\{closure}()

#3 /srv/blkhole/vendor/amphp/amp/lib/Coroutine.php(118): Generator->send('\xC1\xF9\x80\x96\xD3p\xCB\x8D!,\x8A\x8A\xAE\xCC\xC4...')

#4 /srv/blkhole/vendor/amphp/amp/lib/Internal/Placeholder.php(46): Amp\Coroutine->Amp\{closure}(NULL, '\xC1\xF9\x80\x96\xD3p\xCB\x8D!,\x8A\x8A\ in /srv/blkhole/vendor/amphp/http-client/src/Connection/Internal/Http1Parser.php on line 447

[2021-10-29 22:13:40] (The process stopped responding, potentially due to a fatal error or calling exit) torrents listFiles

```

********************************************************************************

**Comment by tuefekci** [comment]
looks like a 32 bit problem $request->setBodySizeLimit((int)(99999 * 1024 * 1024)); is set to 10gb but max int is apparently 2gb :/

**Comment by tuefekci** [comment]
http-client has a bug fix for setting bodysizelimit to unlimited in the next version which should fix this.
